### PR TITLE
Add content to lecture 27, 5/1/23

### PR DESCRIPTION
**Pull request by ColtonMartin**
This commit also changes the title of the markdown file to be consistent with classmates..

### CODE REVIEW

**Comment by kevinaangstadt** [comment]
@pcudd33 please review this PR in the comments

**Comment by pcudd33** [comment]
The name of this file should be Day27Notes.md. And I believe this PR could contain more information. For example, I would include the link to Kevin's website more specifically the link to the final presentation specs. Or you could include more of the information given by the assignment spec due to that being the majority of the work done in class that day.

**Comment by pcudd33** [comment]
You should also add an overview section to give a general format for the structure of the day. Sorry should have added this in the original comment but I just realized.

**Comment by kevinaangstadt** [comment]
@ColtonMartin please make the requested changes

**Pull request merged**
