### PR TITLE
Add notes for lecture 4

### PR DESCRIPTION
**Pull request by jmange19**
This pull request updates lecture 4 to add notes.

Lecture 4 introduced tmux, new text editors, SSH on VScode, and the start of bash scripting.

### CODE REVIEW

**Comment by kevinaangstadt** [comment]
please resolve the conflicts

**Comment by kevinaangstadt** [comment]
@hbsecor please review this PR in the comments

**Comment by jmange19** [comment]
Conflict should be resolved now!

**Comment by kevinaangstadt** [comment]
@hbsecor reminder to review this PR

**Pull request merged**
