### PR TITLE
Create Lecture_Day_15.md

### PR DESCRIPTION
**Pull request by Soko101**
-Add lecture 15 update notes
-lecture notes on testing and variance in bugs with regards to test suites
- Introduces mutation testing and seeding where defects are seeded through manual and automatic (by program) 
-Main body introduces continuous integration and coupling hypothesis
-Summary of story so far
-Conclusion introduces continuous delivery
-Additionally highlights benefits of CI/CD

### CODE REVIEW

**Comment by kevinaangstadt** [comment]
@Peyton2025 please review this PR in the comments

**Comment by Peyton2025** [comment]
Overall, it is very good. The content seems to be good. I would recommend the following changes/options in the future:
- I would recommend smaller commits.
- The merge does not have a message.
- To match the style guide, the world "Definition" should be included before definitions such as mutation testing.
- Definitions should also be bolded.
- Some sentences end in punctuation while others do not.
- The following sentences should be indented:
             -Test suite is not good?
            -Mutant is actually semantics preserving (did not change the outcome of the program) →equivalent mutant programs 
             that are semantically identical and this pass/fail same # of tests.
Once the above changes have been made, this pull request should be approved.

**Comment by kevinaangstadt** [comment]
@Soko101 please make the requested changes

**Comment by Soko101** [comment]
@Peyton2025 I made the necessary changes, as for the definitions I only had 2: CI/CD but I made sure to adhere to all the comments that you suggested so it should be good for merging now

**Pull request merged**
