### PR TITLE
Lecture16

### PR DESCRIPTION
**Pull request by Ayanda2911**
I updated the lecture 16 notes from the outline. 
I am still  waiting on the style guide to be updated to format lecture 16 notes according to the guide.

### CODE REVIEW

**Comment by kevinaangstadt** [comment]
Please fix the merge conflicts

**Comment by kevinaangstadt** [comment]
@hnsengimana please review this PR in the comments

**Review by hnsengimana — CHANGES_REQUESTED** [review]
Overall, the PR looks good. The content shown in class is fully here in the document and correct. There are just a few changes that should be made to align with the style guide. 
Changes:
- Definitions should match the convention shown in the style guide.
- Include an overview of the class day at the beginning of the document.
- Rename the file to Day16Notes.md
- Ensure the formatting including headings matches the Markdown Guide

**Comment by kevinaangstadt** [comment]
Please make the requested changes and add them to this PR :-)

**Comment by kevinaangstadt** [comment]
@Ayanda2911 still waiting for revisions and merge conflicts to approve this PR

**Comment by Ayanda2911** [comment]
I took all the suggestions and implemented them. I hope my changes were sufficient.

**Pull request merged**
