### PR TITLE
Full Lecture notes for class 20

### PR DESCRIPTION
**Pull request by edvinStra**
Full lecture notes of class 20 including code from class. Program not fully functional, see notes from class 21 for rest of code.

### CODE REVIEW

**Comment by kevinaangstadt** [comment]
Please resolve the merge conflicts

**Comment by kevinaangstadt** [comment]
@JamesB5201 please review this PR in the comments

**Comment by edvinStra** [comment]
Resolved merged conflicts

**Comment by kevinaangstadt** [comment]
@edvinStra This appears to have a conflict again

**Comment by edvinStra** [comment]
This conflict should now be resolved

**Comment by kevinaangstadt** [comment]
@JamesB5201 reminder to review this PR

**Comment by JamesB5201** [comment]
After examining my personal notes, both lecture20.md and the python file exactly match the file. Therefore, I can say we high confidence that the lecture20.md file is correct in both its layout with the style guide, its content, and the python file that is included.
In terms of commits, the early commits do not contain a description to describe the commit, instead, they only contain a title. However, starting from commit "Adding Summary Notes From Class 19", the commits begin to follow good practices of commit messages. The commits are wrapped after 72 characters, and along with this, the commit message contains the next steps that you plan to take, which I find extremely helpful. It should be noted that come commits contain minor spelling/grammar errors within them, such as commit "Adding code icnluding import and CLI" or " There were some "Merge Branch" commits as well, however, as someone who had to do these commits, I know that you cannot add a description inherently.
After careful examination, the only fixes I would recommend is to go back and fix some grammar and spelling mistakes in the commits. Other than that, the lecture20.md file and commits look extremely good.
However, as it is, I believe that I can approve this PR due to both the correctness of the content itself, along with the extremely negligible mistakes within a very few of the commits.

**Pull request merged**
