### PR TITLE
Calebsjway Patch 3 - Lecture-3 Update

### PR DESCRIPTION
**Pull request by calebsjway**
Added ~3/4 of data from Lecture 3 on 1/25/2023. Removed unnecessary sections from outline and included relevant information elsewhere.

### CODE REVIEW

**Comment by kevinaangstadt** [comment]
Please resolve the conflict

**Comment by kevinaangstadt** [comment]
@Wjandr please review the PR in the comments

**Review by Wjandr — CHANGES_REQUESTED** [review]
The info provided here is very good, but the formatting could use some work.

Line 2 is the heading for your notes, this should be made into a header by putting # before it. You may also want to consider making headings bold, by putting ** before and after your text.

Some of your lines are not properly separating when I view them in VSCode's markdown viewer. If you put two spaces at the end of a line it will properly insert line breaks.

Your notes are hard to read because there is no text variation. I would insert horizontal lines, using ***, between sections, and make section headers into real headers by using putting # before them. Additionally many of your lines have line breaks in really weird positions. Review what the output of your file looks like and make sure your line breaks are showing up where they are supposed to.

When defining bash commands, it would be more readable to have the name of the command in italics or bold, so that you can clearly see where the command itself is, and where its definition is.

You have some examples of for loops in your notes. These should be put into a code block, by indenting the lines of code by 4 spaces. This will make your code look more code-y.

Any time you define a term or concept, you should put the name of what is being defined in bold, to match what is described in the style guide.

At the end of your notes it has a section which is titled Left to Cover.
I don't know if this was part of the notes, or just the stuff that you still have to put in. Either way this is unfinished and not quite ready to be pulled.

**Comment by kevinaangstadt** [comment]
@calebsjway please make the requested changes

**Review by calebsjway — COMMENTED** [review]
Final update to Lecture-3 class topics, following markdown guidelines and best coding practices.

**Pull request merged**
