### PR TITLE
Update and rename lecture12.md to lecture12_2-27.md

### PR DESCRIPTION
**Pull request by mattabell03**
This pull request completes notes for lecture 12 which was about measuring quality of software testing.

This class covered measuring quality of testing, test suite quality metrics, and issues that can go wrong with testing. This class also gave us an outline on what would be on Exam 1.

### CODE REVIEW

**Comment by kevinaangstadt** [comment]
@rmfust20 please review this PR in the comments

**Review by rmfust20 — CHANGES_REQUESTED** [review]
On lines 56-58, when the file is formatted into markdown it appears as if the "-covered separately" comment is part of the if true case and the if false case nothing happens. Maybe try clarifying by saying: "the if true case is covered separately from the if false case". Other than that the commit looks great, thanks.

**Comment by kevinaangstadt** [comment]
please make the requested changes and then I'll merge this PR :-)

**Review by rmfust20 — APPROVED** [review]
Looks good, thank you.

**Pull request merged**
