### PR TITLE
Updated Day9Notes.md File

### PR DESCRIPTION
**Pull request by JamesB5201**
Finalizes the Day9Notes.md file to contain all the information and notes that were provided during Lecture 9. This includes the warmup exercise, quality assurance, external quality, and rice's theorem.

### CODE REVIEW

**Comment by kevinaangstadt** [comment]
@edvinStra please review this PR in the comments

**Comment by edvinStra** [comment]
After reading through your pull requests, I think your content is correct and good. However, I believe you can add more content, for example about internal quality and how to code for maintainability because I think this was also covered in Day 9. Your commits look good and follow our commit best practices. However, you have a lot of commits for fixing conflicts and renaming/deleting stuff which makes your commit history somewhat confusing but your commit messages are helpful for these commits too. It's not something I am worried about but I would just consider it for future work in git. I approve this PR since it has correct material in it and follows our commit best practices, however, I think some content can be added as described above.

**Comment by kevinaangstadt** [comment]
We will merge this as-is for now. @edvinStra if there is not already an issue open about missing content, you can open one.

**Comment by JamesB5201** [comment]
@edvinStra Thank you for the feedback, I will go back and recheck both my notes and panopto video to fix the sections that are missing. In terms of the branch conflict, I cannot seem to find it on my side, would you be able to point me to the issue?

**Comment by edvinStra** [comment]
This is weird. But now I can't see any conflicts so I think you are all good!

**Pull request merged**
